{% set name = "chrono" %}
{% set version = "8.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/projectchrono/chrono/archive/{{ version }}.tar.gz
  sha256: 02219133c149d5d88f66ea58857a112dea9e3fcf682053f58ff8981337406f28

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('chrono', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - swig 3.0.12
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
  host:
    - eigen
    - python
    - llvm-openmp  # [osx]
  run:
    - llvm-openmp  # [osx]

outputs:
  - name: chrono
    script: clean_python.sh
    test:
      commands:
        - test -f ${PREFIX}/lib/libChronoEngine${SHLIB_EXT}
  - name: pychrono
    script: py_install.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cmake
        - swig 3.0.12
        - llvm-openmp  # [osx]
        - libgomp      # [linux and not aarch64]
      host:
        - {{ pin_subpackage('chrono', exact=True) }}
        - python
        - eigen
        - llvm-openmp  # [osx]
      run:
        - {{ pin_subpackage('chrono', exact=True) }}
        - python
        - llvm-openmp  # [osx]

    test:
      imports:
        - pychrono

about:
  home: https://github.com/projectchrono/chrono
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A physics engine for constrained multi-flexible-body dynamics

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
    - wolfv
