schema_version: 1

context:
  name: chrono
  version: "10.0.0"
  build: 0
  sha256: 7feb9b2f9ab2b3377d4957e00c0bacedc7dbdd6eecb4f337da626b28f4cb99a1

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/projectchrono/chrono/archive/${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: ${{ build }}

outputs:
  - package:
      name: chrono
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        - swig >=4.2,<4.3
        - if: linux and not aarch64
          then: libgomp
        - if: osx
          then: llvm-openmp
        - if: win
          then: m2-base
      host:
        - eigen
        - python
        - if: osx
          then: llvm-openmp
        - if: win
          then: m2-base
      run:
        - eigen
        - if: osx
          then: llvm-openmp
      run_exports:
        - ${{ pin_subpackage('chrono', upper_bound='x.x' ) }}
    build:
      script:
        - if: win
          then: build_chrono.bat
          else: build_chrono.sh
    tests:
      - script:
        - if: win
          then: if not exist %PREFIX%\Library\lib\Chrono_core.lib exit 1
          else: test -f ${PREFIX}/lib/libChrono_core${SHLIB_EXT}

  - package:
      name: pychrono
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - ${{ stdlib("c") }}
        - cmake
        - ninja
        - swig >=4.2,<4.3
        - python
        - if: build_platform != target_platform
          then: cross-python_${{ target_platform }}
        - if: linux and not aarch64
          then: libgomp
        - if: osx
          then: llvm-openmp
        - if: win
          then: m2-base
      host:
        - ${{ pin_subpackage('chrono', exact=True) }}
        - eigen
        - python
        - if: osx
          then: llvm-openmp
        - if: win
          then: m2-base
      run:
        - ${{ pin_subpackage('chrono', exact=True) }}
        - python
        - if: osx
          then: llvm-openmp
    tests:
      - python:
          imports:
            - pychrono
    build:
      script:
        - if: win
          then: build_pychrono.bat
          else: build_pychrono.sh

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A physics engine for constrained multi-flexible-body dynamics
  homepage: https://github.com/projectchrono/chrono

extra:
  recipe-maintainers:
    - traversaro
    - oursland
    - davidbrochart
    - SylvainCorlay
    - wolfv
